In [1]:
# ============================================================
# PHASE 1 — DATASET LOADING & VERIFICATION
# NF-UQ-NIDS-v2
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

# ------------------------------------------------------------
# 1. Dataset path
# ------------------------------------------------------------

DATA_PATH = Path(r"C:\Users\HomePC\Documents\Research\Dataset\NF-UQ-NIDS-v2\Complete_set\data\NF-UQ-NIDS-v2.csv")

# Verify that the file exists
if not DATA_PATH.exists():
    raise FileNotFoundError(
        f"Dataset not found at:\n{DATA_PATH}\n\n"
        "Please update DATA_PATH to the correct CSV location."
    )

print("Dataset found:")
print(DATA_PATH)
print(f"File size: {DATA_PATH.stat().st_size / (1024**2):.2f} MB")

Dataset found:
C:\Users\HomePC\Documents\Research\Dataset\NF-UQ-NIDS-v2\Complete_set\data\NF-UQ-NIDS-v2.csv
File size: 13093.31 MB

In [2]:
# ------------------------------------------------------------
# 2. Inspect column names
# ------------------------------------------------------------

header_df = pd.read_csv(
    DATA_PATH,
    nrows=5
)

print("Number of columns:", len(header_df.columns))
print("\nColumn names:")
for i, col in enumerate(header_df.columns, start=1):
    print(f"{i:02d}. {col}")

Number of columns: 46

Column names:
01. IPV4_SRC_ADDR
02. L4_SRC_PORT
03. IPV4_DST_ADDR
04. L4_DST_PORT
05. PROTOCOL
06. L7_PROTO
07. IN_BYTES
08. IN_PKTS
09. OUT_BYTES
10. OUT_PKTS
11. TCP_FLAGS
12. CLIENT_TCP_FLAGS
13. SERVER_TCP_FLAGS
14. FLOW_DURATION_MILLISECONDS
15. DURATION_IN
16. DURATION_OUT
17. MIN_TTL
18. MAX_TTL
19. LONGEST_FLOW_PKT
20. SHORTEST_FLOW_PKT
21. MIN_IP_PKT_LEN
22. MAX_IP_PKT_LEN
23. SRC_TO_DST_SECOND_BYTES
24. DST_TO_SRC_SECOND_BYTES
25. RETRANSMITTED_IN_BYTES
26. RETRANSMITTED_IN_PKTS
27. RETRANSMITTED_OUT_BYTES
28. RETRANSMITTED_OUT_PKTS
29. SRC_TO_DST_AVG_THROUGHPUT
30. DST_TO_SRC_AVG_THROUGHPUT
31. NUM_PKTS_UP_TO_128_BYTES
32. NUM_PKTS_128_TO_256_BYTES
33. NUM_PKTS_256_TO_512_BYTES
34. NUM_PKTS_512_TO_1024_BYTES
35. NUM_PKTS_1024_TO_1514_BYTES
36. TCP_WIN_MAX_IN
37. TCP_WIN_MAX_OUT
38. ICMP_TYPE
39. ICMP_IPV4_TYPE
40. DNS_QUERY_ID
41. DNS_QUERY_TYPE
42. DNS_TTL_ANSWER
43. FTP_COMMAND_RET_CODE
44. Label
45. Attack
46. Dataset

In [3]:
# ------------------------------------------------------------
# 3. Preview the dataset
# ------------------------------------------------------------

print("\nFirst five records:")
display(header_df)

First five records:

,IPV4_SRC_ADDR,L4_SRC_PORT,IPV4_DST_ADDR,L4_DST_PORT,PROTOCOL,L7_PROTO,IN_BYTES,IN_PKTS,OUT_BYTES,OUT_PKTS,...,TCP_WIN_MAX_OUT,ICMP_TYPE,ICMP_IPV4_TYPE,DNS_QUERY_ID,DNS_QUERY_TYPE,DNS_TTL_ANSWER,FTP_COMMAND_RET_CODE,Label,Attack,Dataset
0,192.168.100.148,65389,192.168.100.7,80,6,7.0,420,3,0,0,...,0,35840,140,0,0,0,0.0,1,DoS,NF-BoT-IoT-v2
1,192.168.100.148,11154,192.168.100.5,80,6,7.0,280,2,40,1,...,0,0,0,0,0,0,0.0,1,DoS,NF-BoT-IoT-v2
2,192.168.1.31,42062,192.168.1.79,1041,6,0.0,44,1,40,1,...,0,0,0,0,0,0,0.0,0,Benign,NF-ToN-IoT-v2
3,192.168.1.34,46849,192.168.1.79,9110,6,0.0,44,1,40,1,...,0,0,0,0,0,0,0.0,0,Benign,NF-ToN-IoT-v2
4,192.168.1.30,50360,192.168.1.152,1084,6,0.0,44,1,40,1,...,0,0,0,0,0,0,0.0,0,Benign,NF-ToN-IoT-v2

In [4]:
# ------------------------------------------------------------
# 4. Identify key columns
# ------------------------------------------------------------

print("\nImportant columns detected:")

for target_col in ["Label", "Attack", "Dataset"]:
    matches = [col for col in header_df.columns if col.strip().lower() == target_col.lower()]

    if matches:
        print(f"{target_col}: {matches}")
    else:
        print(f"{target_col}: NOT FOUND")

Important columns detected:
Label: ['Label']
Attack: ['Attack']
Dataset: ['Dataset']

In [5]:
# ------------------------------------------------------------
# 5. Count total rows safely
# ------------------------------------------------------------

CHUNK_SIZE = 100_000

total_rows = 0

for chunk in pd.read_csv(
    DATA_PATH,
    chunksize=CHUNK_SIZE,
    usecols=[header_df.columns[0]]
):
    total_rows += len(chunk)

print(f"\nTotal rows: {total_rows:,}")
print(f"Total columns: {len(header_df.columns):,}")
print(f"Dataset shape: ({total_rows:,}, {len(header_df.columns)})")

Total rows: 75,987,976
Total columns: 46
Dataset shape: (75,987,976, 46)

In [6]:
# ------------------------------------------------------------
# 6. Inspect data types
# ------------------------------------------------------------

print("\nData types:")
print(header_df.dtypes)

Data types:
IPV4_SRC_ADDR                   object
L4_SRC_PORT                      int64
IPV4_DST_ADDR                   object
L4_DST_PORT                      int64
PROTOCOL                         int64
L7_PROTO                       float64
IN_BYTES                         int64
IN_PKTS                          int64
OUT_BYTES                        int64
OUT_PKTS                         int64
TCP_FLAGS                        int64
CLIENT_TCP_FLAGS                 int64
SERVER_TCP_FLAGS                 int64
FLOW_DURATION_MILLISECONDS       int64
DURATION_IN                      int64
DURATION_OUT                     int64
MIN_TTL                          int64
MAX_TTL                          int64
LONGEST_FLOW_PKT                 int64
SHORTEST_FLOW_PKT                int64
MIN_IP_PKT_LEN                   int64
MAX_IP_PKT_LEN                   int64
SRC_TO_DST_SECOND_BYTES        float64
DST_TO_SRC_SECOND_BYTES        float64
RETRANSMITTED_IN_BYTES           int64
RETRANSMITTED_IN_PKTS            int64
RETRANSMITTED_OUT_BYTES          int64
RETRANSMITTED_OUT_PKTS           int64
SRC_TO_DST_AVG_THROUGHPUT        int64
DST_TO_SRC_AVG_THROUGHPUT        int64
NUM_PKTS_UP_TO_128_BYTES         int64
NUM_PKTS_128_TO_256_BYTES        int64
NUM_PKTS_256_TO_512_BYTES        int64
NUM_PKTS_512_TO_1024_BYTES       int64
NUM_PKTS_1024_TO_1514_BYTES      int64
TCP_WIN_MAX_IN                   int64
TCP_WIN_MAX_OUT                  int64
ICMP_TYPE                        int64
ICMP_IPV4_TYPE                   int64
DNS_QUERY_ID                     int64
DNS_QUERY_TYPE                   int64
DNS_TTL_ANSWER                   int64
FTP_COMMAND_RET_CODE           float64
Label                            int64
Attack                          object
Dataset                         object
dtype: object

In [7]:
# ------------------------------------------------------------
# 7. Locate Label and Attack columns
# ------------------------------------------------------------

def find_column(columns, target):
    matches = [
        col for col in columns
        if col.strip().lower() == target.lower()
    ]

    if len(matches) == 0:
        return None

    if len(matches) > 1:
        raise ValueError(
            f"Multiple columns match '{target}': {matches}"
        )

    return matches[0]


LABEL_COL = find_column(header_df.columns, "Label")
ATTACK_COL = find_column(header_df.columns, "Attack")
DATASET_COL = find_column(header_df.columns, "Dataset")

print("\nDetected columns:")
print("Label   :", LABEL_COL)
print("Attack  :", ATTACK_COL)
print("Dataset :", DATASET_COL)

Detected columns:
Label   : Label
Attack  : Attack
Dataset : Dataset

In [8]:
# ------------------------------------------------------------
# 8. Label distribution
# ------------------------------------------------------------

if LABEL_COL is None:
    raise ValueError(
        "The 'Label' column was not found. "
        "Check the column names printed above."
    )

label_counts = {}

for chunk in pd.read_csv(
    DATA_PATH,
    chunksize=CHUNK_SIZE,
    usecols=[LABEL_COL]
):
    counts = chunk[LABEL_COL].value_counts(dropna=False)

    for value, count in counts.items():
        label_counts[value] = label_counts.get(value, 0) + count

label_distribution = (
    pd.Series(label_counts, name="Instances")
    .sort_values(ascending=False)
)

print("\nLabel Distribution:")
display(label_distribution.to_frame())

Label Distribution:

   Instances
1   50822681
0   25165295

In [9]:
# ------------------------------------------------------------
# 9. Label percentages
# ------------------------------------------------------------

label_summary = pd.DataFrame({
    "Instances": label_distribution,
    "Percentage": (
        label_distribution / label_distribution.sum() * 100
    )
})

label_summary["Percentage"] = label_summary["Percentage"].round(4)

print("\nLabel Summary:")
display(label_summary)

Label Summary:

   Instances  Percentage
1   50822681     66.8825
0   25165295     33.1175

In [10]:
# ------------------------------------------------------------
# 10. Attack-category distribution
# ------------------------------------------------------------

if ATTACK_COL is None:
    raise ValueError(
        "The 'Attack' column was not found. "
        "Check the column names printed above."
    )

attack_counts = {}

for chunk in pd.read_csv(
    DATA_PATH,
    chunksize=CHUNK_SIZE,
    usecols=[ATTACK_COL]
):
    counts = chunk[ATTACK_COL].value_counts(dropna=False)

    for value, count in counts.items():
        attack_counts[value] = attack_counts.get(value, 0) + count

attack_distribution = (
    pd.Series(attack_counts, name="Instances")
    .sort_values(ascending=False)
)

print("\nAttack Category Distribution:")
display(attack_distribution.to_frame())

Attack Category Distribution:

                Instances
Benign           25165295
DDoS             21748351
DoS              17875585
scanning          3781419
Reconnaissance    2633778
xss               2455020
password          1153323
injection          684897
Bot                143097
Brute Force        123982
Infilteration      116361
Exploits            31551
Fuzzers             22310
Backdoor            18978
Generic             16560
mitm                 7723
ransomware           3425
Theft                2431
Analysis             2299
Shellcode            1427
Worms                 164

In [11]:
# ------------------------------------------------------------
# 11. Attack-category percentages
# ------------------------------------------------------------

attack_summary = pd.DataFrame({
    "Instances": attack_distribution,
    "Percentage": (
        attack_distribution / attack_distribution.sum() * 100
    )
})

attack_summary["Percentage"] = attack_summary["Percentage"].round(4)

print("\nAttack Category Summary:")
display(attack_summary)

Attack Category Summary:

                Instances  Percentage
Benign           25165295     33.1175
DDoS             21748351     28.6208
DoS              17875585     23.5242
scanning          3781419      4.9763
Reconnaissance    2633778      3.4660
xss               2455020      3.2308
password          1153323      1.5178
injection          684897      0.9013
Bot                143097      0.1883
Brute Force        123982      0.1632
Infilteration      116361      0.1531
Exploits            31551      0.0415
Fuzzers             22310      0.0294
Backdoor            18978      0.0250
Generic             16560      0.0218
mitm                 7723      0.0102
ransomware           3425      0.0045
Theft                2431      0.0032
Analysis             2299      0.0030
Shellcode            1427      0.0019
Worms                 164      0.0002

In [12]:
# ------------------------------------------------------------
# 12. Expected categories from the study's Table 1
# ------------------------------------------------------------

EXPECTED_ATTACK_CATEGORIES = [
    "Reconnaissance Scanning",
    "Reconnaissance Activities",
    "Password / Brute Force Attacks",
    "Exploit Attacks",
    "Malicious Code Execution",
    "Backdoor Bot Activities",
    "Backdoor Attacks",
    "Internal Compromise Activities",
    "Worm Propagation",
    "Man-in-the-Middle (MITM) Attacks",
    "Unauthorized Data Extraction",
    "Ransomware Attacks"
]

observed_categories = set(
    str(x).strip()
    for x in attack_distribution.index
    if pd.notna(x)
)

expected_categories = set(EXPECTED_ATTACK_CATEGORIES)

missing_from_dataset = expected_categories - observed_categories
unexpected_categories = observed_categories - expected_categories

print("\n" + "=" * 60)
print("CATEGORY VERIFICATION")
print("=" * 60)

print("\nExpected categories found:")
for category in EXPECTED_ATTACK_CATEGORIES:
    status = "FOUND" if category in observed_categories else "NOT FOUND"
    print(f"{status:12} : {category}")

print("\nCategories in dataset but NOT in Table 1:")
if unexpected_categories:
    for category in sorted(unexpected_categories):
        print(" -", category)
else:
    print("None")

============================================================
CATEGORY VERIFICATION
============================================================

Expected categories found:
NOT FOUND    : Reconnaissance Scanning
NOT FOUND    : Reconnaissance Activities
NOT FOUND    : Password / Brute Force Attacks
NOT FOUND    : Exploit Attacks
NOT FOUND    : Malicious Code Execution
NOT FOUND    : Backdoor Bot Activities
NOT FOUND    : Backdoor Attacks
NOT FOUND    : Internal Compromise Activities
NOT FOUND    : Worm Propagation
NOT FOUND    : Man-in-the-Middle (MITM) Attacks
NOT FOUND    : Unauthorized Data Extraction
NOT FOUND    : Ransomware Attacks

Categories in dataset but NOT in Table 1:
 - Analysis
 - Backdoor
 - Benign
 - Bot
 - Brute Force
 - DDoS
 - DoS
 - Exploits
 - Fuzzers
 - Generic
 - Infilteration
 - Reconnaissance
 - Shellcode
 - Theft
 - Worms
 - injection
 - mitm
 - password
 - ransomware
 - scanning
 - xss

In [13]:
# ------------------------------------------------------------
# 13. Dataset metadata column
# ------------------------------------------------------------

if DATASET_COL is not None:

    print("\n'Dataset' column detected.")

    dataset_values = {}

    for chunk in pd.read_csv(
        DATA_PATH,
        chunksize=CHUNK_SIZE,
        usecols=[DATASET_COL]
    ):
        counts = chunk[DATASET_COL].value_counts(dropna=False)

        for value, count in counts.items():
            dataset_values[value] = (
                dataset_values.get(value, 0) + count
            )

    dataset_summary = pd.Series(
        dataset_values,
        name="Instances"
    ).sort_values(ascending=False)

    display(dataset_summary.to_frame())

else:
    print("\n'Dataset' column was not found.")

'Dataset' column detected.

                       Instances
NF-BoT-IoT-v2           37763497
NF-CSE-CIC-IDS2018-v2   18893708
NF-ToN-IoT-v2           16940496
NF-UNSW-NB15-v2          2390275

In [14]:
# ------------------------------------------------------------
# 14. PHASE 1 VERIFICATION REPORT
# ------------------------------------------------------------

print("\n")
print("=" * 70)
print("PHASE 1 — NF-UQ-NIDS-v2 DATASET VERIFICATION REPORT")
print("=" * 70)

print(f"Dataset file       : {DATA_PATH.name}")
print(f"File size          : {DATA_PATH.stat().st_size / (1024**2):.2f} MB")
print(f"Total observations : {total_rows:,}")
print(f"Total features     : {len(header_df.columns):,}")

print("\nKey columns")
print("-" * 70)
print(f"Label column       : {LABEL_COL}")
print(f"Attack column      : {ATTACK_COL}")
print(f"Dataset column     : {DATASET_COL}")

print("\nLabel distribution")
print("-" * 70)
print(label_summary)

print("\nAttack categories")
print("-" * 70)
print(attack_summary)

print("\nExpected categories missing")
print("-" * 70)

if missing_from_dataset:
    for category in sorted(missing_from_dataset):
        print(" -", category)
else:
    print("None")

print("\nUnexpected categories")
print("-" * 70)

if unexpected_categories:
    for category in sorted(unexpected_categories):
        print(" -", category)
else:
    print("None")

print("\n" + "=" * 70)
print("PHASE 1 VERIFICATION COMPLETE")
print("=" * 70)

======================================================================
PHASE 1 — NF-UQ-NIDS-v2 DATASET VERIFICATION REPORT
======================================================================
Dataset file       : NF-UQ-NIDS-v2.csv
File size          : 13093.31 MB
Total observations : 75,987,976
Total features     : 46

Key columns
----------------------------------------------------------------------
Label column       : Label
Attack column      : Attack
Dataset column     : Dataset

Label distribution
----------------------------------------------------------------------
   Instances  Percentage
1   50822681     66.8825
0   25165295     33.1175

Attack categories
----------------------------------------------------------------------
                Instances  Percentage
Benign           25165295     33.1175
DDoS             21748351     28.6208
DoS              17875585     23.5242
scanning          3781419      4.9763
Reconnaissance    2633778      3.4660
xss               2455020      3.2308
password          1153323      1.5178
injection          684897      0.9013
Bot                143097      0.1883
Brute Force        123982      0.1632
Infilteration      116361      0.1531
Exploits            31551      0.0415
Fuzzers             22310      0.0294
Backdoor            18978      0.0250
Generic             16560      0.0218
mitm                 7723      0.0102
ransomware           3425      0.0045
Theft                2431      0.0032
Analysis             2299      0.0030
Shellcode            1427      0.0019
Worms                 164      0.0002

Expected categories missing
----------------------------------------------------------------------
 - Backdoor Attacks
 - Backdoor Bot Activities
 - Exploit Attacks
 - Internal Compromise Activities
 - Malicious Code Execution
 - Man-in-the-Middle (MITM) Attacks
 - Password / Brute Force Attacks
 - Ransomware Attacks
 - Reconnaissance Activities
 - Reconnaissance Scanning
 - Unauthorized Data Extraction
 - Worm Propagation

Unexpected categories
----------------------------------------------------------------------
 - Analysis
 - Backdoor
 - Benign
 - Bot
 - Brute Force
 - DDoS
 - DoS
 - Exploits
 - Fuzzers
 - Generic
 - Infilteration
 - Reconnaissance
 - Shellcode
 - Theft
 - Worms
 - injection
 - mitm
 - password
 - ransomware
 - scanning
 - xss

======================================================================
PHASE 1 VERIFICATION COMPLETE
======================================================================

PHASE 2

In [19]:
import pandas as pd

CHUNK_SIZE = 100_000

for chunk in pd.read_csv(
    DATA_PATH,
    chunksize=CHUNK_SIZE,
    low_memory=True
):
    
    print(f"Processing chunk: {chunk.shape}")

    # Your preprocessing here
    # Your feature engineering here
    # Your model processing here

Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)
Processing chunk: (100000, 46)

In [21]:
df_sample = pd.read_csv(
    DATA_PATH,
    nrows=100_000,
    low_memory=True
)

print(df_sample.shape)
print(df_sample.head())
print(df_sample.info())

(100000, 46)
     IPV4_SRC_ADDR  L4_SRC_PORT  IPV4_DST_ADDR  L4_DST_PORT  PROTOCOL  \
0  192.168.100.148        65389  192.168.100.7           80         6
1  192.168.100.148        11154  192.168.100.5           80         6
2     192.168.1.31        42062   192.168.1.79         1041         6
3     192.168.1.34        46849   192.168.1.79         9110         6
4     192.168.1.30        50360  192.168.1.152         1084         6

   L7_PROTO  IN_BYTES  IN_PKTS  OUT_BYTES  OUT_PKTS  ...  TCP_WIN_MAX_OUT  \
0       7.0       420        3          0         0  ...                0
1       7.0       280        2         40         1  ...                0
2       0.0        44        1         40         1  ...                0
3       0.0        44        1         40         1  ...                0
4       0.0        44        1         40         1  ...                0

   ICMP_TYPE  ICMP_IPV4_TYPE  DNS_QUERY_ID  DNS_QUERY_TYPE  DNS_TTL_ANSWER  \
0      35840             140             0               0               0
1          0               0             0               0               0
2          0               0             0               0               0
3          0               0             0               0               0
4          0               0             0               0               0

   FTP_COMMAND_RET_CODE  Label  Attack        Dataset
0                   0.0      1     DoS  NF-BoT-IoT-v2
1                   0.0      1     DoS  NF-BoT-IoT-v2
2                   0.0      0  Benign  NF-ToN-IoT-v2
3                   0.0      0  Benign  NF-ToN-IoT-v2
4                   0.0      0  Benign  NF-ToN-IoT-v2

[5 rows x 46 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 46 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   IPV4_SRC_ADDR                100000 non-null  object
 1   L4_SRC_PORT                  100000 non-null  int64
 2   IPV4_DST_ADDR                100000 non-null  object
 3   L4_DST_PORT                  100000 non-null  int64
 4   PROTOCOL                     100000 non-null  int64
 5   L7_PROTO                     100000 non-null  float64
 6   IN_BYTES                     100000 non-null  int64
 7   IN_PKTS                      100000 non-null  int64
 8   OUT_BYTES                    100000 non-null  int64
 9   OUT_PKTS                     100000 non-null  int64
 10  TCP_FLAGS                    100000 non-null  int64
 11  CLIENT_TCP_FLAGS             100000 non-null  int64
 12  SERVER_TCP_FLAGS             100000 non-null  int64
 13  FLOW_DURATION_MILLISECONDS   100000 non-null  int64
 14  DURATION_IN                  100000 non-null  int64
 15  DURATION_OUT                 100000 non-null  int64
 16  MIN_TTL                      100000 non-null  int64
 17  MAX_TTL                      100000 non-null  int64
 18  LONGEST_FLOW_PKT             100000 non-null  int64
 19  SHORTEST_FLOW_PKT            100000 non-null  int64
 20  MIN_IP_PKT_LEN               100000 non-null  int64
 21  MAX_IP_PKT_LEN               100000 non-null  int64
 22  SRC_TO_DST_SECOND_BYTES      100000 non-null  float64
 23  DST_TO_SRC_SECOND_BYTES      100000 non-null  float64
 24  RETRANSMITTED_IN_BYTES       100000 non-null  int64
 25  RETRANSMITTED_IN_PKTS        100000 non-null  int64
 26  RETRANSMITTED_OUT_BYTES      100000 non-null  int64
 27  RETRANSMITTED_OUT_PKTS       100000 non-null  int64
 28  SRC_TO_DST_AVG_THROUGHPUT    100000 non-null  int64
 29  DST_TO_SRC_AVG_THROUGHPUT    100000 non-null  int64
 30  NUM_PKTS_UP_TO_128_BYTES     100000 non-null  int64
 31  NUM_PKTS_128_TO_256_BYTES    100000 non-null  int64
 32  NUM_PKTS_256_TO_512_BYTES    100000 non-null  int64
 33  NUM_PKTS_512_TO_1024_BYTES   100000 non-null  int64
 34  NUM_PKTS_1024_TO_1514_BYTES  100000 non-null  int64
 35  TCP_WIN_MAX_IN               100000 non-null  int64
 36  TCP_WIN_MAX_OUT              100000 non-null  int64
 37  ICMP_TYPE                    100000 non-null  int64
 38  ICMP_IPV4_TYPE               100000 non-null  int64
 39  DNS_QUERY_ID                 100000 non-null  int64
 40  DNS_QUERY_TYPE               100000 non-null  int64
 41  DNS_TTL_ANSWER               100000 non-null  int64
 42  FTP_COMMAND_RET_CODE         100000 non-null  float64
 43  Label                        100000 non-null  int64
 44  Attack                       100000 non-null  object
 45  Dataset                      100000 non-null  object
dtypes: float64(4), int64(38), object(4)
memory usage: 35.1+ MB
None

In [22]:
import pandas as pd

CHUNK_SIZE = 100_000

total_rows = 0
chunk_count = 0

for chunk in pd.read_csv(
    DATA_PATH,
    chunksize=CHUNK_SIZE,
    low_memory=True
):
    chunk_count += 1
    total_rows += len(chunk)

    print(
        f"Chunk {chunk_count}: "
        f"{len(chunk):,} rows | "
        f"Total processed: {total_rows:,}"
    )

print("\nDataset loaded/processed successfully.")
print(f"Total chunks: {chunk_count:,}")
print(f"Total rows: {total_rows:,}")

Chunk 1: 100,000 rows | Total processed: 100,000
Chunk 2: 100,000 rows | Total processed: 200,000
Chunk 3: 100,000 rows | Total processed: 300,000
Chunk 4: 100,000 rows | Total processed: 400,000
Chunk 5: 100,000 rows | Total processed: 500,000
Chunk 6: 100,000 rows | Total processed: 600,000
Chunk 7: 100,000 rows | Total processed: 700,000
Chunk 8: 100,000 rows | Total processed: 800,000
Chunk 9: 100,000 rows | Total processed: 900,000
Chunk 10: 100,000 rows | Total processed: 1,000,000
Chunk 11: 100,000 rows | Total processed: 1,100,000
Chunk 12: 100,000 rows | Total processed: 1,200,000
Chunk 13: 100,000 rows | Total processed: 1,300,000
Chunk 14: 100,000 rows | Total processed: 1,400,000
Chunk 15: 100,000 rows | Total processed: 1,500,000
Chunk 16: 100,000 rows | Total processed: 1,600,000
Chunk 17: 100,000 rows | Total processed: 1,700,000
Chunk 18: 100,000 rows | Total processed: 1,800,000
Chunk 19: 100,000 rows | Total processed: 1,900,000
Chunk 20: 100,000 rows | Total processed: 2,000,000
Chunk 21: 100,000 rows | Total processed: 2,100,000
Chunk 22: 100,000 rows | Total processed: 2,200,000
Chunk 23: 100,000 rows | Total processed: 2,300,000
Chunk 24: 100,000 rows | Total processed: 2,400,000
Chunk 25: 100,000 rows | Total processed: 2,500,000
Chunk 26: 100,000 rows | Total processed: 2,600,000
Chunk 27: 100,000 rows | Total processed: 2,700,000
Chunk 28: 100,000 rows | Total processed: 2,800,000
Chunk 29: 100,000 rows | Total processed: 2,900,000
Chunk 30: 100,000 rows | Total processed: 3,000,000
Chunk 31: 100,000 rows | Total processed: 3,100,000
Chunk 32: 100,000 rows | Total processed: 3,200,000
Chunk 33: 100,000 rows | Total processed: 3,300,000
Chunk 34: 100,000 rows | Total processed: 3,400,000
Chunk 35: 100,000 rows | Total processed: 3,500,000
Chunk 36: 100,000 rows | Total processed: 3,600,000
Chunk 37: 100,000 rows | Total processed: 3,700,000
Chunk 38: 100,000 rows | Total processed: 3,800,000
Chunk 39: 100,000 rows | Total processed: 3,900,000
Chunk 40: 100,000 rows | Total processed: 4,000,000
Chunk 41: 100,000 rows | Total processed: 4,100,000
Chunk 42: 100,000 rows | Total processed: 4,200,000
Chunk 43: 100,000 rows | Total processed: 4,300,000
Chunk 44: 100,000 rows | Total processed: 4,400,000
Chunk 45: 100,000 rows | Total processed: 4,500,000
Chunk 46: 100,000 rows | Total processed: 4,600,000
Chunk 47: 100,000 rows | Total processed: 4,700,000
Chunk 48: 100,000 rows | Total processed: 4,800,000
Chunk 49: 100,000 rows | Total processed: 4,900,000
Chunk 50: 100,000 rows | Total processed: 5,000,000
Chunk 51: 100,000 rows | Total processed: 5,100,000
Chunk 52: 100,000 rows | Total processed: 5,200,000
Chunk 53: 100,000 rows | Total processed: 5,300,000
Chunk 54: 100,000 rows | Total processed: 5,400,000
Chunk 55: 100,000 rows | Total processed: 5,500,000
Chunk 56: 100,000 rows | Total processed: 5,600,000
Chunk 57: 100,000 rows | Total processed: 5,700,000
Chunk 58: 100,000 rows | Total processed: 5,800,000
Chunk 59: 100,000 rows | Total processed: 5,900,000
Chunk 60: 100,000 rows | Total processed: 6,000,000
Chunk 61: 100,000 rows | Total processed: 6,100,000
Chunk 62: 100,000 rows | Total processed: 6,200,000
Chunk 63: 100,000 rows | Total processed: 6,300,000
Chunk 64: 100,000 rows | Total processed: 6,400,000
Chunk 65: 100,000 rows | Total processed: 6,500,000
Chunk 66: 100,000 rows | Total processed: 6,600,000
Chunk 67: 100,000 rows | Total processed: 6,700,000
Chunk 68: 100,000 rows | Total processed: 6,800,000
Chunk 69: 100,000 rows | Total processed: 6,900,000
Chunk 70: 100,000 rows | Total processed: 7,000,000
Chunk 71: 100,000 rows | Total processed: 7,100,000
Chunk 72: 100,000 rows | Total processed: 7,200,000
Chunk 73: 100,000 rows | Total processed: 7,300,000
Chunk 74: 100,000 rows | Total processed: 7,400,000
Chunk 75: 100,000 rows | Total processed: 7,500,000
Chunk 76: 100,000 rows | Total processed: 7,600,000
Chunk 77: 100,000 rows | Total processed: 7,700,000
Chunk 78: 100,000 rows | Total processed: 7,800,000
Chunk 79: 100,000 rows | Total processed: 7,900,000
Chunk 80: 100,000 rows | Total processed: 8,000,000
Chunk 81: 100,000 rows | Total processed: 8,100,000
Chunk 82: 100,000 rows | Total processed: 8,200,000
Chunk 83: 100,000 rows | Total processed: 8,300,000
Chunk 84: 100,000 rows | Total processed: 8,400,000
Chunk 85: 100,000 rows | Total processed: 8,500,000
Chunk 86: 100,000 rows | Total processed: 8,600,000
Chunk 87: 100,000 rows | Total processed: 8,700,000
Chunk 88: 100,000 rows | Total processed: 8,800,000
Chunk 89: 100,000 rows | Total processed: 8,900,000
Chunk 90: 100,000 rows | Total processed: 9,000,000
Chunk 91: 100,000 rows | Total processed: 9,100,000
Chunk 92: 100,000 rows | Total processed: 9,200,000
Chunk 93: 100,000 rows | Total processed: 9,300,000
Chunk 94: 100,000 rows | Total processed: 9,400,000
Chunk 95: 100,000 rows | Total processed: 9,500,000
Chunk 96: 100,000 rows | Total processed: 9,600,000
Chunk 97: 100,000 rows | Total processed: 9,700,000
Chunk 98: 100,000 rows | Total processed: 9,800,000
Chunk 99: 100,000 rows | Total processed: 9,900,000
Chunk 100: 100,000 rows | Total processed: 10,000,000
Chunk 101: 100,000 rows | Total processed: 10,100,000
Chunk 102: 100,000 rows | Total processed: 10,200,000
Chunk 103: 100,000 rows | Total processed: 10,300,000
Chunk 104: 100,000 rows | Total processed: 10,400,000
Chunk 105: 100,000 rows | Total processed: 10,500,000
Chunk 106: 100,000 rows | Total processed: 10,600,000
Chunk 107: 100,000 rows | Total processed: 10,700,000
Chunk 108: 100,000 rows | Total processed: 10,800,000
Chunk 109: 100,000 rows | Total processed: 10,900,000
Chunk 110: 100,000 rows | Total processed: 11,000,000
Chunk 111: 100,000 rows | Total processed: 11,100,000
Chunk 112: 100,000 rows | Total processed: 11,200,000
Chunk 113: 100,000 rows | Total processed: 11,300,000
Chunk 114: 100,000 rows | Total processed: 11,400,000
Chunk 115: 100,000 rows | Total processed: 11,500,000
Chunk 116: 100,000 rows | Total processed: 11,600,000
Chunk 117: 100,000 rows | Total processed: 11,700,000
Chunk 118: 100,000 rows | Total processed: 11,800,000
Chunk 119: 100,000 rows | Total processed: 11,900,000
Chunk 120: 100,000 rows | Total processed: 12,000,000
Chunk 121: 100,000 rows | Total processed: 12,100,000
Chunk 122: 100,000 rows | Total processed: 12,200,000
Chunk 123: 100,000 rows | Total processed: 12,300,000
Chunk 124: 100,000 rows | Total processed: 12,400,000
Chunk 125: 100,000 rows | Total processed: 12,500,000
Chunk 126: 100,000 rows | Total processed: 12,600,000
Chunk 127: 100,000 rows | Total processed: 12,700,000
Chunk 128: 100,000 rows | Total processed: 12,800,000
Chunk 129: 100,000 rows | Total processed: 12,900,000
Chunk 130: 100,000 rows | Total processed: 13,000,000
Chunk 131: 100,000 rows | Total processed: 13,100,000
Chunk 132: 100,000 rows | Total processed: 13,200,000
Chunk 133: 100,000 rows | Total processed: 13,300,000
Chunk 134: 100,000 rows | Total processed: 13,400,000
Chunk 135: 100,000 rows | Total processed: 13,500,000
Chunk 136: 100,000 rows | Total processed: 13,600,000
Chunk 137: 100,000 rows | Total processed: 13,700,000
Chunk 138: 100,000 rows | Total processed: 13,800,000
Chunk 139: 100,000 rows | Total processed: 13,900,000
Chunk 140: 100,000 rows | Total processed: 14,000,000
Chunk 141: 100,000 rows | Total processed: 14,100,000
Chunk 142: 100,000 rows | Total processed: 14,200,000
Chunk 143: 100,000 rows | Total processed: 14,300,000
Chunk 144: 100,000 rows | Total processed: 14,400,000
Chunk 145: 100,000 rows | Total processed: 14,500,000
Chunk 146: 100,000 rows | Total processed: 14,600,000
Chunk 147: 100,000 rows | Total processed: 14,700,000
Chunk 148: 100,000 rows | Total processed: 14,800,000
Chunk 149: 100,000 rows | Total processed: 14,900,000
Chunk 150: 100,000 rows | Total processed: 15,000,000
Chunk 151: 100,000 rows | Total processed: 15,100,000
Chunk 152: 100,000 rows | Total processed: 15,200,000
Chunk 153: 100,000 rows | Total processed: 15,300,000
Chunk 154: 100,000 rows | Total processed: 15,400,000
Chunk 155: 100,000 rows | Total processed: 15,500,000
Chunk 156: 100,000 rows | Total processed: 15,600,000
Chunk 157: 100,000 rows | Total processed: 15,700,000
Chunk 158: 100,000 rows | Total processed: 15,800,000
Chunk 159: 100,000 rows | Total processed: 15,900,000
Chunk 160: 100,000 rows | Total processed: 16,000,000
Chunk 161: 100,000 rows | Total processed: 16,100,000
Chunk 162: 100,000 rows | Total processed: 16,200,000
Chunk 163: 100,000 rows | Total processed: 16,300,000
Chunk 164: 100,000 rows | Total processed: 16,400,000
Chunk 165: 100,000 rows | Total processed: 16,500,000
Chunk 166: 100,000 rows | Total processed: 16,600,000
Chunk 167: 100,000 rows | Total processed: 16,700,000
Chunk 168: 100,000 rows | Total processed: 16,800,000
Chunk 169: 100,000 rows | Total processed: 16,900,000
Chunk 170: 100,000 rows | Total processed: 17,000,000
Chunk 171: 100,000 rows | Total processed: 17,100,000
Chunk 172: 100,000 rows | Total processed: 17,200,000
Chunk 173: 100,000 rows | Total processed: 17,300,000
Chunk 174: 100,000 rows | Total processed: 17,400,000
Chunk 175: 100,000 rows | Total processed: 17,500,000
Chunk 176: 100,000 rows | Total processed: 17,600,000
Chunk 177: 100,000 rows | Total processed: 17,700,000
Chunk 178: 100,000 rows | Total processed: 17,800,000
Chunk 179: 100,000 rows | Total processed: 17,900,000
Chunk 180: 100,000 rows | Total processed: 18,000,000
Chunk 181: 100,000 rows | Total processed: 18,100,000
Chunk 182: 100,000 rows | Total processed: 18,200,000
Chunk 183: 100,000 rows | Total processed: 18,300,000
Chunk 184: 100,000 rows | Total processed: 18,400,000
Chunk 185: 100,000 rows | Total processed: 18,500,000
Chunk 186: 100,000 rows | Total processed: 18,600,000
Chunk 187: 100,000 rows | Total processed: 18,700,000
Chunk 188: 100,000 rows | Total processed: 18,800,000
Chunk 189: 100,000 rows | Total processed: 18,900,000
Chunk 190: 100,000 rows | Total processed: 19,000,000
Chunk 191: 100,000 rows | Total processed: 19,100,000
Chunk 192: 100,000 rows | Total processed: 19,200,000
Chunk 193: 100,000 rows | Total processed: 19,300,000
Chunk 194: 100,000 rows | Total processed: 19,400,000
Chunk 195: 100,000 rows | Total processed: 19,500,000
Chunk 196: 100,000 rows | Total processed: 19,600,000
Chunk 197: 100,000 rows | Total processed: 19,700,000
Chunk 198: 100,000 rows | Total processed: 19,800,000
Chunk 199: 100,000 rows | Total processed: 19,900,000
Chunk 200: 100,000 rows | Total processed: 20,000,000
Chunk 201: 100,000 rows | Total processed: 20,100,000
Chunk 202: 100,000 rows | Total processed: 20,200,000
Chunk 203: 100,000 rows | Total processed: 20,300,000
Chunk 204: 100,000 rows | Total processed: 20,400,000
Chunk 205: 100,000 rows | Total processed: 20,500,000
Chunk 206: 100,000 rows | Total processed: 20,600,000
Chunk 207: 100,000 rows | Total processed: 20,700,000
Chunk 208: 100,000 rows | Total processed: 20,800,000
Chunk 209: 100,000 rows | Total processed: 20,900,000
Chunk 210: 100,000 rows | Total processed: 21,000,000
Chunk 211: 100,000 rows | Total processed: 21,100,000
Chunk 212: 100,000 rows | Total processed: 21,200,000
Chunk 213: 100,000 rows | Total processed: 21,300,000
Chunk 214: 100,000 rows | Total processed: 21,400,000
Chunk 215: 100,000 rows | Total processed: 21,500,000
Chunk 216: 100,000 rows | Total processed: 21,600,000
Chunk 217: 100,000 rows | Total processed: 21,700,000
Chunk 218: 100,000 rows | Total processed: 21,800,000
Chunk 219: 100,000 rows | Total processed: 21,900,000
Chunk 220: 100,000 rows | Total processed: 22,000,000
Chunk 221: 100,000 rows | Total processed: 22,100,000
Chunk 222: 100,000 rows | Total processed: 22,200,000
Chunk 223: 100,000 rows | Total processed: 22,300,000
Chunk 224: 100,000 rows | Total processed: 22,400,000
Chunk 225: 100,000 rows | Total processed: 22,500,000
Chunk 226: 100,000 rows | Total processed: 22,600,000
Chunk 227: 100,000 rows | Total processed: 22,700,000
Chunk 228: 100,000 rows | Total processed: 22,800,000
Chunk 229: 100,000 rows | Total processed: 22,900,000
Chunk 230: 100,000 rows | Total processed: 23,000,000
Chunk 231: 100,000 rows | Total processed: 23,100,000
Chunk 232: 100,000 rows | Total processed: 23,200,000
Chunk 233: 100,000 rows | Total processed: 23,300,000
Chunk 234: 100,000 rows | Total processed: 23,400,000
Chunk 235: 100,000 rows | Total processed: 23,500,000
Chunk 236: 100,000 rows | Total processed: 23,600,000
Chunk 237: 100,000 rows | Total processed: 23,700,000
Chunk 238: 100,000 rows | Total processed: 23,800,000
Chunk 239: 100,000 rows | Total processed: 23,900,000
Chunk 240: 100,000 rows | Total processed: 24,000,000
Chunk 241: 100,000 rows | Total processed: 24,100,000
Chunk 242: 100,000 rows | Total processed: 24,200,000
Chunk 243: 100,000 rows | Total processed: 24,300,000
Chunk 244: 100,000 rows | Total processed: 24,400,000
Chunk 245: 100,000 rows | Total processed: 24,500,000
Chunk 246: 100,000 rows | Total processed: 24,600,000
Chunk 247: 100,000 rows | Total processed: 24,700,000
Chunk 248: 100,000 rows | Total processed: 24,800,000
Chunk 249: 100,000 rows | Total processed: 24,900,000
Chunk 250: 100,000 rows | Total processed: 25,000,000
Chunk 251: 100,000 rows | Total processed: 25,100,000
Chunk 252: 100,000 rows | Total processed: 25,200,000
Chunk 253: 100,000 rows | Total processed: 25,300,000
Chunk 254: 100,000 rows | Total processed: 25,400,000
Chunk 255: 100,000 rows | Total processed: 25,500,000
Chunk 256: 100,000 rows | Total processed: 25,600,000
Chunk 257: 100,000 rows | Total processed: 25,700,000
Chunk 258: 100,000 rows | Total processed: 25,800,000
Chunk 259: 100,000 rows | Total processed: 25,900,000
Chunk 260: 100,000 rows | Total processed: 26,000,000
Chunk 261: 100,000 rows | Total processed: 26,100,000
Chunk 262: 100,000 rows | Total processed: 26,200,000
Chunk 263: 100,000 rows | Total processed: 26,300,000
Chunk 264: 100,000 rows | Total processed: 26,400,000
Chunk 265: 100,000 rows | Total processed: 26,500,000
Chunk 266: 100,000 rows | Total processed: 26,600,000
Chunk 267: 100,000 rows | Total processed: 26,700,000
Chunk 268: 100,000 rows | Total processed: 26,800,000
Chunk 269: 100,000 rows | Total processed: 26,900,000
Chunk 270: 100,000 rows | Total processed: 27,000,000
Chunk 271: 100,000 rows | Total processed: 27,100,000
Chunk 272: 100,000 rows | Total processed: 27,200,000
Chunk 273: 100,000 rows | Total processed: 27,300,000
Chunk 274: 100,000 rows | Total processed: 27,400,000
Chunk 275: 100,000 rows | Total processed: 27,500,000
Chunk 276: 100,000 rows | Total processed: 27,600,000
Chunk 277: 100,000 rows | Total processed: 27,700,000
Chunk 278: 100,000 rows | Total processed: 27,800,000
Chunk 279: 100,000 rows | Total processed: 27,900,000
Chunk 280: 100,000 rows | Total processed: 28,000,000
Chunk 281: 100,000 rows | Total processed: 28,100,000
Chunk 282: 100,000 rows | Total processed: 28,200,000
Chunk 283: 100,000 rows | Total processed: 28,300,000
Chunk 284: 100,000 rows | Total processed: 28,400,000
Chunk 285: 100,000 rows | Total processed: 28,500,000
Chunk 286: 100,000 rows | Total processed: 28,600,000
Chunk 287: 100,000 rows | Total processed: 28,700,000
Chunk 288: 100,000 rows | Total processed: 28,800,000
Chunk 289: 100,000 rows | Total processed: 28,900,000
Chunk 290: 100,000 rows | Total processed: 29,000,000
Chunk 291: 100,000 rows | Total processed: 29,100,000
Chunk 292: 100,000 rows | Total processed: 29,200,000
Chunk 293: 100,000 rows | Total processed: 29,300,000
Chunk 294: 100,000 rows | Total processed: 29,400,000
Chunk 295: 100,000 rows | Total processed: 29,500,000
Chunk 296: 100,000 rows | Total processed: 29,600,000
Chunk 297: 100,000 rows | Total processed: 29,700,000
Chunk 298: 100,000 rows | Total processed: 29,800,000
Chunk 299: 100,000 rows | Total processed: 29,900,000
Chunk 300: 100,000 rows | Total processed: 30,000,000
Chunk 301: 100,000 rows | Total processed: 30,100,000
Chunk 302: 100,000 rows | Total processed: 30,200,000
Chunk 303: 100,000 rows | Total processed: 30,300,000
Chunk 304: 100,000 rows | Total processed: 30,400,000
Chunk 305: 100,000 rows | Total processed: 30,500,000
Chunk 306: 100,000 rows | Total processed: 30,600,000
Chunk 307: 100,000 rows | Total processed: 30,700,000
Chunk 308: 100,000 rows | Total processed: 30,800,000
Chunk 309: 100,000 rows | Total processed: 30,900,000
Chunk 310: 100,000 rows | Total processed: 31,000,000
Chunk 311: 100,000 rows | Total processed: 31,100,000
Chunk 312: 100,000 rows | Total processed: 31,200,000
Chunk 313: 100,000 rows | Total processed: 31,300,000
Chunk 314: 100,000 rows | Total processed: 31,400,000
Chunk 315: 100,000 rows | Total processed: 31,500,000
Chunk 316: 100,000 rows | Total processed: 31,600,000
Chunk 317: 100,000 rows | Total processed: 31,700,000
Chunk 318: 100,000 rows | Total processed: 31,800,000
Chunk 319: 100,000 rows | Total processed: 31,900,000
Chunk 320: 100,000 rows | Total processed: 32,000,000
Chunk 321: 100,000 rows | Total processed: 32,100,000
Chunk 322: 100,000 rows | Total processed: 32,200,000
Chunk 323: 100,000 rows | Total processed: 32,300,000
Chunk 324: 100,000 rows | Total processed: 32,400,000
Chunk 325: 100,000 rows | Total processed: 32,500,000
Chunk 326: 100,000 rows | Total processed: 32,600,000
Chunk 327: 100,000 rows | Total processed: 32,700,000
Chunk 328: 100,000 rows | Total processed: 32,800,000
Chunk 329: 100,000 rows | Total processed: 32,900,000
Chunk 330: 100,000 rows | Total processed: 33,000,000
Chunk 331: 100,000 rows | Total processed: 33,100,000
Chunk 332: 100,000 rows | Total processed: 33,200,000
Chunk 333: 100,000 rows | Total processed: 33,300,000
Chunk 334: 100,000 rows | Total processed: 33,400,000
Chunk 335: 100,000 rows | Total processed: 33,500,000
Chunk 336: 100,000 rows | Total processed: 33,600,000
Chunk 337: 100,000 rows | Total processed: 33,700,000
Chunk 338: 100,000 rows | Total processed: 33,800,000
Chunk 339: 100,000 rows | Total processed: 33,900,000
Chunk 340: 100,000 rows | Total processed: 34,000,000
Chunk 341: 100,000 rows | Total processed: 34,100,000
Chunk 342: 100,000 rows | Total processed: 34,200,000
Chunk 343: 100,000 rows | Total processed: 34,300,000
Chunk 344: 100,000 rows | Total processed: 34,400,000
Chunk 345: 100,000 rows | Total processed: 34,500,000
Chunk 346: 100,000 rows | Total processed: 34,600,000
Chunk 347: 100,000 rows | Total processed: 34,700,000
Chunk 348: 100,000 rows | Total processed: 34,800,000
Chunk 349: 100,000 rows | Total processed: 34,900,000
Chunk 350: 100,000 rows | Total processed: 35,000,000
Chunk 351: 100,000 rows | Total processed: 35,100,000
Chunk 352: 100,000 rows | Total processed: 35,200,000
Chunk 353: 100,000 rows | Total processed: 35,300,000
Chunk 354: 100,000 rows | Total processed: 35,400,000
Chunk 355: 100,000 rows | Total processed: 35,500,000
Chunk 356: 100,000 rows | Total processed: 35,600,000
Chunk 357: 100,000 rows | Total processed: 35,700,000
Chunk 358: 100,000 rows | Total processed: 35,800,000
Chunk 359: 100,000 rows | Total processed: 35,900,000
Chunk 360: 100,000 rows | Total processed: 36,000,000
Chunk 361: 100,000 rows | Total processed: 36,100,000
Chunk 362: 100,000 rows | Total processed: 36,200,000
Chunk 363: 100,000 rows | Total processed: 36,300,000
Chunk 364: 100,000 rows | Total processed: 36,400,000
Chunk 365: 100,000 rows | Total processed: 36,500,000
Chunk 366: 100,000 rows | Total processed: 36,600,000
Chunk 367: 100,000 rows | Total processed: 36,700,000
Chunk 368: 100,000 rows | Total processed: 36,800,000
Chunk 369: 100,000 rows | Total processed: 36,900,000
Chunk 370: 100,000 rows | Total processed: 37,000,000
Chunk 371: 100,000 rows | Total processed: 37,100,000
Chunk 372: 100,000 rows | Total processed: 37,200,000
Chunk 373: 100,000 rows | Total processed: 37,300,000
Chunk 374: 100,000 rows | Total processed: 37,400,000

In [23]:
# ------------------------------------------------------------
# Verify required columns
# ------------------------------------------------------------

REQUIRED_COLUMNS = ["Label", "Attack"]

# Read only a few rows to inspect the column names
sample = pd.read_csv(DATA_PATH, nrows=5)

missing_required = [
    col for col in REQUIRED_COLUMNS
    if col not in sample.columns
]

if missing_required:
    raise ValueError(
        f"Required columns missing from dataset: {missing_required}"
    )

print("Required columns verified:")
for col in REQUIRED_COLUMNS:
    print(f"✓ {col}")

Required columns verified:
✓ Label
✓ Attack

In [24]:
# ------------------------------------------------------------
# Process dataset in chunks
# ------------------------------------------------------------

CHUNK_SIZE = 100_000
total_rows = 0
chunk_count = 0

for chunk in pd.read_csv(
    DATA_PATH,
    chunksize=CHUNK_SIZE,
    low_memory=True
):
    chunk_count += 1
    total_rows += len(chunk)

    print(
        f"Chunk {chunk_count}: "
        f"{len(chunk):,} rows | "
        f"Total processed: {total_rows:,}"
    )

    # Your preprocessing/model code goes here

print("\nDataset processed successfully.")
print(f"Total chunks: {chunk_count:,}")
print(f"Total rows: {total_rows:,}")

Chunk 1: 100,000 rows | Total processed: 100,000
Chunk 2: 100,000 rows | Total processed: 200,000
Chunk 3: 100,000 rows | Total processed: 300,000
Chunk 4: 100,000 rows | Total processed: 400,000
Chunk 5: 100,000 rows | Total processed: 500,000
Chunk 6: 100,000 rows | Total processed: 600,000
Chunk 7: 100,000 rows | Total processed: 700,000
Chunk 8: 100,000 rows | Total processed: 800,000
Chunk 9: 100,000 rows | Total processed: 900,000
Chunk 10: 100,000 rows | Total processed: 1,000,000
Chunk 11: 100,000 rows | Total processed: 1,100,000
Chunk 12: 100,000 rows | Total processed: 1,200,000
Chunk 13: 100,000 rows | Total processed: 1,300,000
Chunk 14: 100,000 rows | Total processed: 1,400,000
Chunk 15: 100,000 rows | Total processed: 1,500,000
Chunk 16: 100,000 rows | Total processed: 1,600,000
Chunk 17: 100,000 rows | Total processed: 1,700,000
Chunk 18: 100,000 rows | Total processed: 1,800,000
Chunk 19: 100,000 rows | Total processed: 1,900,000
Chunk 20: 100,000 rows | Total processed: 2,000,000
Chunk 21: 100,000 rows | Total processed: 2,100,000
Chunk 22: 100,000 rows | Total processed: 2,200,000
Chunk 23: 100,000 rows | Total processed: 2,300,000
Chunk 24: 100,000 rows | Total processed: 2,400,000
Chunk 25: 100,000 rows | Total processed: 2,500,000
Chunk 26: 100,000 rows | Total processed: 2,600,000
Chunk 27: 100,000 rows | Total processed: 2,700,000
Chunk 28: 100,000 rows | Total processed: 2,800,000
Chunk 29: 100,000 rows | Total processed: 2,900,000
Chunk 30: 100,000 rows | Total processed: 3,000,000
Chunk 31: 100,000 rows | Total processed: 3,100,000
Chunk 32: 100,000 rows | Total processed: 3,200,000
Chunk 33: 100,000 rows | Total processed: 3,300,000
Chunk 34: 100,000 rows | Total processed: 3,400,000
Chunk 35: 100,000 rows | Total processed: 3,500,000
Chunk 36: 100,000 rows | Total processed: 3,600,000
Chunk 37: 100,000 rows | Total processed: 3,700,000
Chunk 38: 100,000 rows | Total processed: 3,800,000
Chunk 39: 100,000 rows | Total processed: 3,900,000
Chunk 40: 100,000 rows | Total processed: 4,000,000
Chunk 41: 100,000 rows | Total processed: 4,100,000
Chunk 42: 100,000 rows | Total processed: 4,200,000
Chunk 43: 100,000 rows | Total processed: 4,300,000
Chunk 44: 100,000 rows | Total processed: 4,400,000
Chunk 45: 100,000 rows | Total processed: 4,500,000
Chunk 46: 100,000 rows | Total processed: 4,600,000
Chunk 47: 100,000 rows | Total processed: 4,700,000
Chunk 48: 100,000 rows | Total processed: 4,800,000
Chunk 49: 100,000 rows | Total processed: 4,900,000
Chunk 50: 100,000 rows | Total processed: 5,000,000
Chunk 51: 100,000 rows | Total processed: 5,100,000
Chunk 52: 100,000 rows | Total processed: 5,200,000
Chunk 53: 100,000 rows | Total processed: 5,300,000
Chunk 54: 100,000 rows | Total processed: 5,400,000
Chunk 55: 100,000 rows | Total processed: 5,500,000
Chunk 56: 100,000 rows | Total processed: 5,600,000
Chunk 57: 100,000 rows | Total processed: 5,700,000
Chunk 58: 100,000 rows | Total processed: 5,800,000
Chunk 59: 100,000 rows | Total processed: 5,900,000
Chunk 60: 100,000 rows | Total processed: 6,000,000
Chunk 61: 100,000 rows | Total processed: 6,100,000
Chunk 62: 100,000 rows | Total processed: 6,200,000
Chunk 63: 100,000 rows | Total processed: 6,300,000
Chunk 64: 100,000 rows | Total processed: 6,400,000
Chunk 65: 100,000 rows | Total processed: 6,500,000
Chunk 66: 100,000 rows | Total processed: 6,600,000
Chunk 67: 100,000 rows | Total processed: 6,700,000
Chunk 68: 100,000 rows | Total processed: 6,800,000
Chunk 69: 100,000 rows | Total processed: 6,900,000
Chunk 70: 100,000 rows | Total processed: 7,000,000
Chunk 71: 100,000 rows | Total processed: 7,100,000
Chunk 72: 100,000 rows | Total processed: 7,200,000
Chunk 73: 100,000 rows | Total processed: 7,300,000
Chunk 74: 100,000 rows | Total processed: 7,400,000
Chunk 75: 100,000 rows | Total processed: 7,500,000
Chunk 76: 100,000 rows | Total processed: 7,600,000
Chunk 77: 100,000 rows | Total processed: 7,700,000
Chunk 78: 100,000 rows | Total processed: 7,800,000
Chunk 79: 100,000 rows | Total processed: 7,900,000
Chunk 80: 100,000 rows | Total processed: 8,000,000
Chunk 81: 100,000 rows | Total processed: 8,100,000
Chunk 82: 100,000 rows | Total processed: 8,200,000
Chunk 83: 100,000 rows | Total processed: 8,300,000
Chunk 84: 100,000 rows | Total processed: 8,400,000
Chunk 85: 100,000 rows | Total processed: 8,500,000
Chunk 86: 100,000 rows | Total processed: 8,600,000
Chunk 87: 100,000 rows | Total processed: 8,700,000
Chunk 88: 100,000 rows | Total processed: 8,800,000
Chunk 89: 100,000 rows | Total processed: 8,900,000
Chunk 90: 100,000 rows | Total processed: 9,000,000
Chunk 91: 100,000 rows | Total processed: 9,100,000
Chunk 92: 100,000 rows | Total processed: 9,200,000
Chunk 93: 100,000 rows | Total processed: 9,300,000
Chunk 94: 100,000 rows | Total processed: 9,400,000
Chunk 95: 100,000 rows | Total processed: 9,500,000
Chunk 96: 100,000 rows | Total processed: 9,600,000
Chunk 97: 100,000 rows | Total processed: 9,700,000
Chunk 98: 100,000 rows | Total processed: 9,800,000
Chunk 99: 100,000 rows | Total processed: 9,900,000
Chunk 100: 100,000 rows | Total processed: 10,000,000
Chunk 101: 100,000 rows | Total processed: 10,100,000
Chunk 102: 100,000 rows | Total processed: 10,200,000
Chunk 103: 100,000 rows | Total processed: 10,300,000
Chunk 104: 100,000 rows | Total processed: 10,400,000
Chunk 105: 100,000 rows | Total processed: 10,500,000
Chunk 106: 100,000 rows | Total processed: 10,600,000
Chunk 107: 100,000 rows | Total processed: 10,700,000
Chunk 108: 100,000 rows | Total processed: 10,800,000
Chunk 109: 100,000 rows | Total processed: 10,900,000
Chunk 110: 100,000 rows | Total processed: 11,000,000
Chunk 111: 100,000 rows | Total processed: 11,100,000
Chunk 112: 100,000 rows | Total processed: 11,200,000
Chunk 113: 100,000 rows | Total processed: 11,300,000
Chunk 114: 100,000 rows | Total processed: 11,400,000
Chunk 115: 100,000 rows | Total processed: 11,500,000
Chunk 116: 100,000 rows | Total processed: 11,600,000
Chunk 117: 100,000 rows | Total processed: 11,700,000
Chunk 118: 100,000 rows | Total processed: 11,800,000
Chunk 119: 100,000 rows | Total processed: 11,900,000
Chunk 120: 100,000 rows | Total processed: 12,000,000
Chunk 121: 100,000 rows | Total processed: 12,100,000
Chunk 122: 100,000 rows | Total processed: 12,200,000
Chunk 123: 100,000 rows | Total processed: 12,300,000
Chunk 124: 100,000 rows | Total processed: 12,400,000
Chunk 125: 100,000 rows | Total processed: 12,500,000
Chunk 126: 100,000 rows | Total processed: 12,600,000
Chunk 127: 100,000 rows | Total processed: 12,700,000
Chunk 128: 100,000 rows | Total processed: 12,800,000
Chunk 129: 100,000 rows | Total processed: 12,900,000
Chunk 130: 100,000 rows | Total processed: 13,000,000
Chunk 131: 100,000 rows | Total processed: 13,100,000
Chunk 132: 100,000 rows | Total processed: 13,200,000
Chunk 133: 100,000 rows | Total processed: 13,300,000
Chunk 134: 100,000 rows | Total processed: 13,400,000
Chunk 135: 100,000 rows | Total processed: 13,500,000
Chunk 136: 100,000 rows | Total processed: 13,600,000
Chunk 137: 100,000 rows | Total processed: 13,700,000
Chunk 138: 100,000 rows | Total processed: 13,800,000
Chunk 139: 100,000 rows | Total processed: 13,900,000
Chunk 140: 100,000 rows | Total processed: 14,000,000
Chunk 141: 100,000 rows | Total processed: 14,100,000
Chunk 142: 100,000 rows | Total processed: 14,200,000
Chunk 143: 100,000 rows | Total processed: 14,300,000
Chunk 144: 100,000 rows | Total processed: 14,400,000
Chunk 145: 100,000 rows | Total processed: 14,500,000
Chunk 146: 100,000 rows | Total processed: 14,600,000
Chunk 147: 100,000 rows | Total processed: 14,700,000
Chunk 148: 100,000 rows | Total processed: 14,800,000
Chunk 149: 100,000 rows | Total processed: 14,900,000
Chunk 150: 100,000 rows | Total processed: 15,000,000
Chunk 151: 100,000 rows | Total processed: 15,100,000
Chunk 152: 100,000 rows | Total processed: 15,200,000
Chunk 153: 100,000 rows | Total processed: 15,300,000
Chunk 154: 100,000 rows | Total processed: 15,400,000
Chunk 155: 100,000 rows | Total processed: 15,500,000
Chunk 156: 100,000 rows | Total processed: 15,600,000
Chunk 157: 100,000 rows | Total processed: 15,700,000
Chunk 158: 100,000 rows | Total processed: 15,800,000
Chunk 159: 100,000 rows | Total processed: 15,900,000
Chunk 160: 100,000 rows | Total processed: 16,000,000
Chunk 161: 100,000 rows | Total processed: 16,100,000
Chunk 162: 100,000 rows | Total processed: 16,200,000
Chunk 163: 100,000 rows | Total processed: 16,300,000
Chunk 164: 100,000 rows | Total processed: 16,400,000
Chunk 165: 100,000 rows | Total processed: 16,500,000
Chunk 166: 100,000 rows | Total processed: 16,600,000
Chunk 167: 100,000 rows | Total processed: 16,700,000
Chunk 168: 100,000 rows | Total processed: 16,800,000
Chunk 169: 100,000 rows | Total processed: 16,900,000
Chunk 170: 100,000 rows | Total processed: 17,000,000
Chunk 171: 100,000 rows | Total processed: 17,100,000
Chunk 172: 100,000 rows | Total processed: 17,200,000
Chunk 173: 100,000 rows | Total processed: 17,300,000
Chunk 174: 100,000 rows | Total processed: 17,400,000
Chunk 175: 100,000 rows | Total processed: 17,500,000
Chunk 176: 100,000 rows | Total processed: 17,600,000
Chunk 177: 100,000 rows | Total processed: 17,700,000
Chunk 178: 100,000 rows | Total processed: 17,800,000
Chunk 179: 100,000 rows | Total processed: 17,900,000
Chunk 180: 100,000 rows | Total processed: 18,000,000
Chunk 181: 100,000 rows | Total processed: 18,100,000
Chunk 182: 100,000 rows | Total processed: 18,200,000
Chunk 183: 100,000 rows | Total processed: 18,300,000
Chunk 184: 100,000 rows | Total processed: 18,400,000
Chunk 185: 100,000 rows | Total processed: 18,500,000
Chunk 186: 100,000 rows | Total processed: 18,600,000
Chunk 187: 100,000 rows | Total processed: 18,700,000
Chunk 188: 100,000 rows | Total processed: 18,800,000
Chunk 189: 100,000 rows | Total processed: 18,900,000
Chunk 190: 100,000 rows | Total processed: 19,000,000
Chunk 191: 100,000 rows | Total processed: 19,100,000
Chunk 192: 100,000 rows | Total processed: 19,200,000
Chunk 193: 100,000 rows | Total processed: 19,300,000
Chunk 194: 100,000 rows | Total processed: 19,400,000
Chunk 195: 100,000 rows | Total processed: 19,500,000
Chunk 196: 100,000 rows | Total processed: 19,600,000
Chunk 197: 100,000 rows | Total processed: 19,700,000
Chunk 198: 100,000 rows | Total processed: 19,800,000
Chunk 199: 100,000 rows | Total processed: 19,900,000
Chunk 200: 100,000 rows | Total processed: 20,000,000
Chunk 201: 100,000 rows | Total processed: 20,100,000
Chunk 202: 100,000 rows | Total processed: 20,200,000
Chunk 203: 100,000 rows | Total processed: 20,300,000
Chunk 204: 100,000 rows | Total processed: 20,400,000
Chunk 205: 100,000 rows | Total processed: 20,500,000
Chunk 206: 100,000 rows | Total processed: 20,600,000
Chunk 207: 100,000 rows | Total processed: 20,700,000
Chunk 208: 100,000 rows | Total processed: 20,800,000
Chunk 209: 100,000 rows | Total processed: 20,900,000
Chunk 210: 100,000 rows | Total processed: 21,000,000
Chunk 211: 100,000 rows | Total processed: 21,100,000
Chunk 212: 100,000 rows | Total processed: 21,200,000
Chunk 213: 100,000 rows | Total processed: 21,300,000
Chunk 214: 100,000 rows | Total processed: 21,400,000
Chunk 215: 100,000 rows | Total processed: 21,500,000
Chunk 216: 100,000 rows | Total processed: 21,600,000
Chunk 217: 100,000 rows | Total processed: 21,700,000
Chunk 218: 100,000 rows | Total processed: 21,800,000
Chunk 219: 100,000 rows | Total processed: 21,900,000
Chunk 220: 100,000 rows | Total processed: 22,000,000
Chunk 221: 100,000 rows | Total processed: 22,100,000
Chunk 222: 100,000 rows | Total processed: 22,200,000
Chunk 223: 100,000 rows | Total processed: 22,300,000
Chunk 224: 100,000 rows | Total processed: 22,400,000
Chunk 225: 100,000 rows | Total processed: 22,500,000
Chunk 226: 100,000 rows | Total processed: 22,600,000
Chunk 227: 100,000 rows | Total processed: 22,700,000
Chunk 228: 100,000 rows | Total processed: 22,800,000
Chunk 229: 100,000 rows | Total processed: 22,900,000
Chunk 230: 100,000 rows | Total processed: 23,000,000
Chunk 231: 100,000 rows | Total processed: 23,100,000
Chunk 232: 100,000 rows | Total processed: 23,200,000
Chunk 233: 100,000 rows | Total processed: 23,300,000
Chunk 234: 100,000 rows | Total processed: 23,400,000
Chunk 235: 100,000 rows | Total processed: 23,500,000
Chunk 236: 100,000 rows | Total processed: 23,600,000
Chunk 237: 100,000 rows | Total processed: 23,700,000
Chunk 238: 100,000 rows | Total processed: 23,800,000
Chunk 239: 100,000 rows | Total processed: 23,900,000
Chunk 240: 100,000 rows | Total processed: 24,000,000
Chunk 241: 100,000 rows | Total processed: 24,100,000
Chunk 242: 100,000 rows | Total processed: 24,200,000
Chunk 243: 100,000 rows | Total processed: 24,300,000
Chunk 244: 100,000 rows | Total processed: 24,400,000
Chunk 245: 100,000 rows | Total processed: 24,500,000
Chunk 246: 100,000 rows | Total processed: 24,600,000
Chunk 247: 100,000 rows | Total processed: 24,700,000
Chunk 248: 100,000 rows | Total processed: 24,800,000
Chunk 249: 100,000 rows | Total processed: 24,900,000
Chunk 250: 100,000 rows | Total processed: 25,000,000
Chunk 251: 100,000 rows | Total processed: 25,100,000
Chunk 252: 100,000 rows | Total processed: 25,200,000
Chunk 253: 100,000 rows | Total processed: 25,300,000
Chunk 254: 100,000 rows | Total processed: 25,400,000
Chunk 255: 100,000 rows | Total processed: 25,500,000
Chunk 256: 100,000 rows | Total processed: 25,600,000
Chunk 257: 100,000 rows | Total processed: 25,700,000
Chunk 258: 100,000 rows | Total processed: 25,800,000
Chunk 259: 100,000 rows | Total processed: 25,900,000
Chunk 260: 100,000 rows | Total processed: 26,000,000
Chunk 261: 100,000 rows | Total processed: 26,100,000
Chunk 262: 100,000 rows | Total processed: 26,200,000
Chunk 263: 100,000 rows | Total processed: 26,300,000
Chunk 264: 100,000 rows | Total processed: 26,400,000
Chunk 265: 100,000 rows | Total processed: 26,500,000
Chunk 266: 100,000 rows | Total processed: 26,600,000
Chunk 267: 100,000 rows | Total processed: 26,700,000
Chunk 268: 100,000 rows | Total processed: 26,800,000
Chunk 269: 100,000 rows | Total processed: 26,900,000
Chunk 270: 100,000 rows | Total processed: 27,000,000
Chunk 271: 100,000 rows | Total processed: 27,100,000
Chunk 272: 100,000 rows | Total processed: 27,200,000
Chunk 273: 100,000 rows | Total processed: 27,300,000
Chunk 274: 100,000 rows | Total processed: 27,400,000
Chunk 275: 100,000 rows | Total processed: 27,500,000
Chunk 276: 100,000 rows | Total processed: 27,600,000
Chunk 277: 100,000 rows | Total processed: 27,700,000
Chunk 278: 100,000 rows | Total processed: 27,800,000
Chunk 279: 100,000 rows | Total processed: 27,900,000
Chunk 280: 100,000 rows | Total processed: 28,000,000
Chunk 281: 100,000 rows | Total processed: 28,100,000
Chunk 282: 100,000 rows | Total processed: 28,200,000
Chunk 283: 100,000 rows | Total processed: 28,300,000
Chunk 284: 100,000 rows | Total processed: 28,400,000
Chunk 285: 100,000 rows | Total processed: 28,500,000
Chunk 286: 100,000 rows | Total processed: 28,600,000
Chunk 287: 100,000 rows | Total processed: 28,700,000
Chunk 288: 100,000 rows | Total processed: 28,800,000
Chunk 289: 100,000 rows | Total processed: 28,900,000
Chunk 290: 100,000 rows | Total processed: 29,000,000
Chunk 291: 100,000 rows | Total processed: 29,100,000
Chunk 292: 100,000 rows | Total processed: 29,200,000
Chunk 293: 100,000 rows | Total processed: 29,300,000
Chunk 294: 100,000 rows | Total processed: 29,400,000
Chunk 295: 100,000 rows | Total processed: 29,500,000
Chunk 296: 100,000 rows | Total processed: 29,600,000
Chunk 297: 100,000 rows | Total processed: 29,700,000
Chunk 298: 100,000 rows | Total processed: 29,800,000
Chunk 299: 100,000 rows | Total processed: 29,900,000
Chunk 300: 100,000 rows | Total processed: 30,000,000
Chunk 301: 100,000 rows | Total processed: 30,100,000
Chunk 302: 100,000 rows | Total processed: 30,200,000
Chunk 303: 100,000 rows | Total processed: 30,300,000
Chunk 304: 100,000 rows | Total processed: 30,400,000
Chunk 305: 100,000 rows | Total processed: 30,500,000
Chunk 306: 100,000 rows | Total processed: 30,600,000
Chunk 307: 100,000 rows | Total processed: 30,700,000
Chunk 308: 100,000 rows | Total processed: 30,800,000
Chunk 309: 100,000 rows | Total processed: 30,900,000
Chunk 310: 100,000 rows | Total processed: 31,000,000
Chunk 311: 100,000 rows | Total processed: 31,100,000
Chunk 312: 100,000 rows | Total processed: 31,200,000
Chunk 313: 100,000 rows | Total processed: 31,300,000
Chunk 314: 100,000 rows | Total processed: 31,400,000
Chunk 315: 100,000 rows | Total processed: 31,500,000
Chunk 316: 100,000 rows | Total processed: 31,600,000
Chunk 317: 100,000 rows | Total processed: 31,700,000
Chunk 318: 100,000 rows | Total processed: 31,800,000
Chunk 319: 100,000 rows | Total processed: 31,900,000
Chunk 320: 100,000 rows | Total processed: 32,000,000
Chunk 321: 100,000 rows | Total processed: 32,100,000
Chunk 322: 100,000 rows | Total processed: 32,200,000
Chunk 323: 100,000 rows | Total processed: 32,300,000
Chunk 324: 100,000 rows | Total processed: 32,400,000
Chunk 325: 100,000 rows | Total processed: 32,500,000
Chunk 326: 100,000 rows | Total processed: 32,600,000
Chunk 327: 100,000 rows | Total processed: 32,700,000
Chunk 328: 100,000 rows | Total processed: 32,800,000
Chunk 329: 100,000 rows | Total processed: 32,900,000
Chunk 330: 100,000 rows | Total processed: 33,000,000
Chunk 331: 100,000 rows | Total processed: 33,100,000
Chunk 332: 100,000 rows | Total processed: 33,200,000
Chunk 333: 100,000 rows | Total processed: 33,300,000
Chunk 334: 100,000 rows | Total processed: 33,400,000
Chunk 335: 100,000 rows | Total processed: 33,500,000
Chunk 336: 100,000 rows | Total processed: 33,600,000
Chunk 337: 100,000 rows | Total processed: 33,700,000
Chunk 338: 100,000 rows | Total processed: 33,800,000
Chunk 339: 100,000 rows | Total processed: 33,900,000
Chunk 340: 100,000 rows | Total processed: 34,000,000
Chunk 341: 100,000 rows | Total processed: 34,100,000
Chunk 342: 100,000 rows | Total processed: 34,200,000
Chunk 343: 100,000 rows | Total processed: 34,300,000
Chunk 344: 100,000 rows | Total processed: 34,400,000
Chunk 345: 100,000 rows | Total processed: 34,500,000
Chunk 346: 100,000 rows | Total processed: 34,600,000
Chunk 347: 100,000 rows | Total processed: 34,700,000
Chunk 348: 100,000 rows | Total processed: 34,800,000
Chunk 349: 100,000 rows | Total processed: 34,900,000
Chunk 350: 100,000 rows | Total processed: 35,000,000
Chunk 351: 100,000 rows | Total processed: 35,100,000
Chunk 352: 100,000 rows | Total processed: 35,200,000
Chunk 353: 100,000 rows | Total processed: 35,300,000
Chunk 354: 100,000 rows | Total processed: 35,400,000
Chunk 355: 100,000 rows | Total processed: 35,500,000
Chunk 356: 100,000 rows | Total processed: 35,600,000
Chunk 357: 100,000 rows | Total processed: 35,700,000
Chunk 358: 100,000 rows | Total processed: 35,800,000
Chunk 359: 100,000 rows | Total processed: 35,900,000
Chunk 360: 100,000 rows | Total processed: 36,000,000
Chunk 361: 100,000 rows | Total processed: 36,100,000
Chunk 362: 100,000 rows | Total processed: 36,200,000
Chunk 363: 100,000 rows | Total processed: 36,300,000
Chunk 364: 100,000 rows | Total processed: 36,400,000
Chunk 365: 100,000 rows | Total processed: 36,500,000
Chunk 366: 100,000 rows | Total processed: 36,600,000
Chunk 367: 100,000 rows | Total processed: 36,700,000
Chunk 368: 100,000 rows | Total processed: 36,800,000
Chunk 369: 100,000 rows | Total processed: 36,900,000
Chunk 370: 100,000 rows | Total processed: 37,000,000
Chunk 371: 100,000 rows | Total processed: 37,100,000
Chunk 372: 100,000 rows | Total processed: 37,200,000
Chunk 373: 100,000 rows | Total processed: 37,300,000
Chunk 374: 100,000 rows | Total processed: 37,400,000

In [27]:
# ------------------------------------------------------------
# Missing-value and infinite-value analysis
# ------------------------------------------------------------

CHUNK_SIZE = 100_000

missing_counts = None
infinity_counts = None
total_rows = 0

for chunk in pd.read_csv(
    DATA_PATH,
    chunksize=CHUNK_SIZE,
    low_memory=True
):

    total_rows += len(chunk)

    # --------------------------------------------------------
    # Missing values
    # --------------------------------------------------------

    chunk_missing = chunk.isna().sum()

    if missing_counts is None:
        missing_counts = chunk_missing
    else:
        missing_counts = missing_counts.add(
            chunk_missing,
            fill_value=0
        )

    # --------------------------------------------------------
    # Infinite values
    # --------------------------------------------------------

    numeric_columns = chunk.select_dtypes(
        include=[np.number]
    ).columns

    chunk_infinity = np.isinf(
        chunk[numeric_columns]
    ).sum()

    if infinity_counts is None:
        infinity_counts = chunk_infinity
    else:
        infinity_counts = infinity_counts.add(
            chunk_infinity,
            fill_value=0
        )


# ------------------------------------------------------------
# Missing-value percentages
# ------------------------------------------------------------

missing_percentage = (
    missing_counts / total_rows * 100
).round(4)

missing_table = pd.DataFrame({
    "Missing Values": missing_counts.astype(int),
    "Percentage": missing_percentage
})

missing_table = missing_table[
    missing_table["Missing Values"] > 0
].sort_values(
    "Missing Values",
    ascending=False
)

print("Missing-value summary:")

if missing_table.empty:
    print("✓ No missing values detected.")
else:
    display(missing_table)


# ------------------------------------------------------------
# Infinite-value analysis
# ------------------------------------------------------------

infinity_summary = (
    infinity_counts[infinity_counts > 0]
    .sort_values(ascending=False)
)

print("\nInfinite-value summary:")

if infinity_summary.empty:
    print("✓ No infinite values detected.")
else:
    display(
        infinity_summary.to_frame("Infinite Values")
    )

Missing-value summary:
✓ No missing values detected.

Infinite-value summary:
✓ No infinite values detected.

In [ ]:
# ------------------------------------------------------------
# Convert infinite values to NaN
# ------------------------------------------------------------

df[numeric_columns] = df[numeric_columns].replace(
    [np.inf, -np.inf],
    np.nan
)

print("Infinite values converted to NaN.")

In [ ]:
remaining_inf = np.isinf(
    df[numeric_columns]
).sum().sum()

print(
    f"Remaining infinite values: {remaining_inf}"
)